vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /uploads/products
            upload_destination: '%kernel.project_dir%/public/uploads/products'

        category:
            uri_prefix: /uploads/category
            upload_destination: '%kernel.project_dir%/public/uploads/category'
